[package]
name = "spacecurve"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
getrandom = { version = "0.4", features = ["wasm_js"] }
num-traits = "0.2.19"
rand = "0.10"
rand_chacha = "0.10"
smallvec = "1.15.1"
thiserror = "2.0"

[dev-dependencies]
criterion = "0.8"
paste = "1.0"
proptest = "1.9"

[[bench]]
name="patterns"
harness=false

[[bench]]
name="ops"
harness=false

[lib]
doctest = false
